import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

export const runtime = 'edge'

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' })

const BASE_URL = 'https://getproheadshot.com'
const OG_IMAGE = `${BASE_URL}/og-image.jpg`

export const metadata: Metadata = {
  metadataBase: new URL(BASE_URL),
  title: {
    default: 'AI Headshot Generator for LinkedIn & Resume | ProHeadshot AI',
    template: '%s | ProHeadshot AI',
  },
  description: 'Upload one photo and get 9 professional headshots in 3 styles — LinkedIn, Resume, and Corporate. From $9.9. No signup required.',
  keywords: [
    'AI headshot generator',
    'professional headshot AI',
    'LinkedIn headshot generator',
    'AI profile photo',
    'resume photo AI',
    'corporate headshot generator',
    'online headshot maker',
  ],
  authors: [{ name: 'ProHeadshot AI', url: BASE_URL }],
  creator: 'ProHeadshot AI',
  openGraph: {
    type: 'website',
    url: BASE_URL,
    siteName: 'ProHeadshot AI',
    title: 'AI Headshot Generator — 9 Professional Photos from $9.9',
    description: 'Upload a selfie → get 9 studio-quality headshots in 3 styles. LinkedIn, Resume & Corporate ready. No signup. Preview free.',
    images: [
      {
        url: OG_IMAGE,
        width: 1200,
        height: 630,
        alt: 'ProHeadshot AI — Professional Headshots Generated by AI',
      },
    ],
    locale: 'en_US',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'AI Headshot Generator — 9 Professional Photos from $9.9',
    description: 'Upload a selfie → get 9 studio-quality headshots. LinkedIn, Resume & Corporate ready. No signup.',
    images: [OG_IMAGE],
    creator: '@proheadshotai',
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  alternates: {
    canonical: BASE_URL,
  },
  verification: {
    google: 'OWG_jGJrtwyt6k_ffmpXiEB9ZuAmzVj12kyHrH52cL8',
  },
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={inter.variable}>
      <body>{children}</body>
    </html>
  )
}
